# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.








pkgdatadir = $(datadir)/relion
pkgincludedir = $(includedir)/relion
pkglibdir = $(libdir)/relion
pkglibexecdir = $(libexecdir)/relion
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
am__append_1 = src/mpi.cpp \
 src/autopicker_mpi.cpp \
 src/ctffind_runner_mpi.cpp \
 src/particle_polisher_mpi.cpp \
 src/particle_sorter_mpi.cpp \
 src/particle_segmenter_mpi.cpp \
 src/subtractingmic_mpi.cpp \
 src/preprocessing_mpi.cpp \
 src/ml_optimiser_mpi.cpp

am__append_2 = src/mpi.h \
 src/autopicker_mpi.h \
 src/ctffind_runner_mpi.h \
 src/particle_polisher_mpi.h \
 src/particle_sorter_mpi.h \
 src/particle_segmenter_mpi.h \
 src/subtractingmic_mpi.h \
 src/preprocessing_mpi.h \
 src/ml_optimiser_mpi.h

am__append_3 = src/displayer.cpp \
 src/gui_entries.cpp \
 src/gui_jobwindow.cpp \
 src/gui_mainwindow.cpp \
 src/manualpicker.cpp 

am__append_4 = src/displayer.h \
 src/gui_entries.h \
 src/gui_jobwindow.h \
 src/gui_mainwindow.h \
 src/manualpicker.h 

bin_PROGRAMS = project$(EXEEXT) reconstruct$(EXEEXT) refine$(EXEEXT) \
	preprocess$(EXEEXT) postprocess$(EXEEXT) autopick$(EXEEXT) \
	particle_polish$(EXEEXT) particle_sort$(EXEEXT) \
	run_ctffind$(EXEEXT) star_compare$(EXEEXT) \
	find_tiltpairs$(EXEEXT) tiltpair_plot$(EXEEXT) \
	particle_segmentation$(EXEEXT) subtract_micrograph$(EXEEXT) \
	$(am__EXEEXT_1) $(am__EXEEXT_2) mask_create$(EXEEXT) \
	stack_create$(EXEEXT) image_handler$(EXEEXT) \
	find_tiltpairs$(EXEEXT) tiltpair_plot$(EXEEXT)
am__append_5 = refine_mpi preprocess_mpi autopick_mpi particle_polish_mpi particle_sort_mpi run_ctffind_mpi particle_segmentation_mpi subtract_micrograph_mpi
am__append_6 = manualpick display maingui 	
subdir = .
DIST_COMMON = README $(am__configure_deps) \
	$(am__nobase_relion_include_HEADERS_DIST) $(dist_bin_SCRIPTS) \
	$(dist_noinst_SCRIPTS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(srcdir)/relion.pc.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS compile config.guess config.sub depcomp \
	install-sh ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = relion-${RELION_API_VERSION}.pc
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(bindir)" "$(DESTDIR)$(pkgconfigdir)" \
	"$(DESTDIR)$(relion_includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
librelion_1.4_la_LIBADD =
am__librelion_1.4_la_SOURCES_DIST = src/args.cpp \
	src/assembly.cpp src/autopicker.cpp src/backprojector.cpp \
	src/complex.cpp src/ctf.cpp src/ctffind_runner.cpp \
	src/error.cpp src/euler.cpp src/exp_model.cpp src/fftw.cpp \
	src/filename.cpp src/funcs.cpp src/healpix_sampling.cpp \
	src/image.cpp src/mask.cpp src/matrix1d.cpp src/matrix2d.cpp \
	src/memory.cpp src/metadata_container.cpp \
	src/metadata_label.cpp src/metadata_table.cpp src/ml_model.cpp \
	src/ml_optimiser.cpp src/multidim_array.cpp \
	src/numerical_recipes.cpp src/parallel.cpp \
	src/particle_polisher.cpp src/particle_sorter.cpp \
	src/particle_segmenter.cpp src/subtractingmic.cpp \
	src/postprocessing.cpp src/preprocessing.cpp src/projector.cpp \
	src/strings.cpp src/symmetries.cpp src/tabfuncs.cpp \
	src/time.cpp src/transformations.cpp \
	src/Healpix_2.15a/cxxutils.cc \
	src/Healpix_2.15a/healpix_base.cc src/mpi.cpp \
	src/autopicker_mpi.cpp src/ctffind_runner_mpi.cpp \
	src/particle_polisher_mpi.cpp src/particle_sorter_mpi.cpp \
	src/particle_segmenter_mpi.cpp src/subtractingmic_mpi.cpp \
	src/preprocessing_mpi.cpp src/ml_optimiser_mpi.cpp \
	src/displayer.cpp src/gui_entries.cpp src/gui_jobwindow.cpp \
	src/gui_mainwindow.cpp src/manualpicker.cpp
am__dirstamp = $(am__leading_dot)dirstamp
am__objects_1 = src/mpi.lo src/autopicker_mpi.lo \
	src/ctffind_runner_mpi.lo \
	src/particle_polisher_mpi.lo \
	src/particle_sorter_mpi.lo \
	src/particle_segmenter_mpi.lo \
	src/subtractingmic_mpi.lo \
	src/preprocessing_mpi.lo \
	src/ml_optimiser_mpi.lo
am__objects_2 = src/displayer.lo src/gui_entries.lo \
	src/gui_jobwindow.lo src/gui_mainwindow.lo \
	src/manualpicker.lo
am_librelion_1.4_la_OBJECTS = src/args.lo \
	src/assembly.lo src/autopicker.lo src/backprojector.lo \
	src/complex.lo src/ctf.lo src/ctffind_runner.lo src/error.lo \
	src/euler.lo src/exp_model.lo src/fftw.lo src/filename.lo \
	src/funcs.lo src/healpix_sampling.lo src/image.lo src/mask.lo \
	src/matrix1d.lo src/matrix2d.lo src/memory.lo \
	src/metadata_container.lo src/metadata_label.lo \
	src/metadata_table.lo src/ml_model.lo src/ml_optimiser.lo \
	src/multidim_array.lo src/numerical_recipes.lo src/parallel.lo \
	src/particle_polisher.lo src/particle_sorter.lo \
	src/particle_segmenter.lo src/subtractingmic.lo \
	src/postprocessing.lo src/preprocessing.lo src/projector.lo \
	src/strings.lo src/symmetries.lo src/tabfuncs.lo src/time.lo \
	src/transformations.lo src/Healpix_2.15a/cxxutils.lo \
	src/Healpix_2.15a/healpix_base.lo $(am__objects_1) \
	$(am__objects_2)
librelion_1.4_la_OBJECTS =  \
	$(am_librelion_1.4_la_OBJECTS)
librelion_1.4_la_LINK = $(LIBTOOL) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) \
	$(librelion_1.4_la_LDFLAGS) $(LDFLAGS) -o $@
am__EXEEXT_1 = refine_mpi$(EXEEXT) \
	preprocess_mpi$(EXEEXT) autopick_mpi$(EXEEXT) \
	particle_polish_mpi$(EXEEXT) \
	particle_sort_mpi$(EXEEXT) \
	run_ctffind_mpi$(EXEEXT) \
	particle_segmentation_mpi$(EXEEXT) \
	subtract_micrograph_mpi$(EXEEXT)
am__EXEEXT_2 = manualpick$(EXEEXT) display$(EXEEXT) \
	maingui$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)
am_autopick_OBJECTS = src/apps/autopick.$(OBJEXT)
autopick_OBJECTS = $(am_autopick_OBJECTS)
autopick_DEPENDENCIES = $(RelionLibs)
am_autopick_mpi_OBJECTS = src/apps/autopick_mpi.$(OBJEXT)
autopick_mpi_OBJECTS = $(am_autopick_mpi_OBJECTS)
autopick_mpi_DEPENDENCIES = $(RelionLibs)
am_display_OBJECTS = src/apps/display.$(OBJEXT)
display_OBJECTS = $(am_display_OBJECTS)
display_DEPENDENCIES = $(RelionLibs)
am_find_tiltpairs_OBJECTS = src/apps/find_tiltpairs.$(OBJEXT)
find_tiltpairs_OBJECTS = $(am_find_tiltpairs_OBJECTS)
find_tiltpairs_DEPENDENCIES = $(RelionLibs)
am_image_handler_OBJECTS = src/apps/image_handler.$(OBJEXT)
image_handler_OBJECTS = $(am_image_handler_OBJECTS)
image_handler_DEPENDENCIES = $(RelionLibs)
am_maingui_OBJECTS = src/apps/maingui.$(OBJEXT)
maingui_OBJECTS = $(am_maingui_OBJECTS)
maingui_DEPENDENCIES = $(RelionLibs)
am_manualpick_OBJECTS = src/apps/manualpick.$(OBJEXT)
manualpick_OBJECTS = $(am_manualpick_OBJECTS)
manualpick_DEPENDENCIES = $(RelionLibs)
am_mask_create_OBJECTS = src/apps/mask_create.$(OBJEXT)
mask_create_OBJECTS = $(am_mask_create_OBJECTS)
mask_create_DEPENDENCIES = $(RelionLibs)
am_particle_polish_OBJECTS = src/apps/particle_polish.$(OBJEXT)
particle_polish_OBJECTS = $(am_particle_polish_OBJECTS)
particle_polish_DEPENDENCIES = $(RelionLibs)
am_particle_polish_mpi_OBJECTS =  \
	src/apps/particle_polish_mpi.$(OBJEXT)
particle_polish_mpi_OBJECTS = $(am_particle_polish_mpi_OBJECTS)
particle_polish_mpi_DEPENDENCIES = $(RelionLibs)
am_particle_segmentation_OBJECTS =  \
	src/apps/particle_segmentation.$(OBJEXT)
particle_segmentation_OBJECTS = $(am_particle_segmentation_OBJECTS)
particle_segmentation_DEPENDENCIES = $(RelionLibs)
am_particle_segmentation_mpi_OBJECTS =  \
	src/apps/particle_segmentation_mpi.$(OBJEXT)
particle_segmentation_mpi_OBJECTS =  \
	$(am_particle_segmentation_mpi_OBJECTS)
particle_segmentation_mpi_DEPENDENCIES = $(RelionLibs)
am_particle_sort_OBJECTS = src/apps/particle_sort.$(OBJEXT)
particle_sort_OBJECTS = $(am_particle_sort_OBJECTS)
particle_sort_DEPENDENCIES = $(RelionLibs)
am_particle_sort_mpi_OBJECTS = src/apps/particle_sort_mpi.$(OBJEXT)
particle_sort_mpi_OBJECTS = $(am_particle_sort_mpi_OBJECTS)
particle_sort_mpi_DEPENDENCIES = $(RelionLibs)
am_postprocess_OBJECTS = src/apps/postprocess.$(OBJEXT)
postprocess_OBJECTS = $(am_postprocess_OBJECTS)
postprocess_DEPENDENCIES = $(RelionLibs)
am_preprocess_OBJECTS = src/apps/preprocess.$(OBJEXT)
preprocess_OBJECTS = $(am_preprocess_OBJECTS)
preprocess_DEPENDENCIES = $(RelionLibs)
am_preprocess_mpi_OBJECTS = src/apps/preprocess_mpi.$(OBJEXT)
preprocess_mpi_OBJECTS = $(am_preprocess_mpi_OBJECTS)
preprocess_mpi_DEPENDENCIES = $(RelionLibs)
am_project_OBJECTS = src/apps/project.$(OBJEXT)
project_OBJECTS = $(am_project_OBJECTS)
project_DEPENDENCIES = $(RelionLibs)
am_reconstruct_OBJECTS = src/apps/reconstruct.$(OBJEXT)
reconstruct_OBJECTS = $(am_reconstruct_OBJECTS)
reconstruct_DEPENDENCIES = $(RelionLibs)
am_refine_OBJECTS = src/apps/refine.$(OBJEXT)
refine_OBJECTS = $(am_refine_OBJECTS)
refine_DEPENDENCIES = $(RelionLibs)
am_refine_mpi_OBJECTS = src/apps/refine_mpi.$(OBJEXT)
refine_mpi_OBJECTS = $(am_refine_mpi_OBJECTS)
refine_mpi_DEPENDENCIES = $(RelionLibs)
am_run_ctffind_OBJECTS = src/apps/run_ctffind.$(OBJEXT)
run_ctffind_OBJECTS = $(am_run_ctffind_OBJECTS)
run_ctffind_DEPENDENCIES = $(RelionLibs)
am_run_ctffind_mpi_OBJECTS = src/apps/run_ctffind_mpi.$(OBJEXT)
run_ctffind_mpi_OBJECTS = $(am_run_ctffind_mpi_OBJECTS)
run_ctffind_mpi_DEPENDENCIES = $(RelionLibs)
am_stack_create_OBJECTS = src/apps/stack_create.$(OBJEXT)
stack_create_OBJECTS = $(am_stack_create_OBJECTS)
stack_create_DEPENDENCIES = $(RelionLibs)
am_star_compare_OBJECTS = src/apps/star_compare.$(OBJEXT)
star_compare_OBJECTS = $(am_star_compare_OBJECTS)
star_compare_DEPENDENCIES = $(RelionLibs)
am_subtract_micrograph_OBJECTS =  \
	src/apps/subtract_micrograph.$(OBJEXT)
subtract_micrograph_OBJECTS = $(am_subtract_micrograph_OBJECTS)
subtract_micrograph_DEPENDENCIES = $(RelionLibs)
am_subtract_micrograph_mpi_OBJECTS =  \
	src/apps/subtract_micrograph_mpi.$(OBJEXT)
subtract_micrograph_mpi_OBJECTS =  \
	$(am_subtract_micrograph_mpi_OBJECTS)
subtract_micrograph_mpi_DEPENDENCIES = $(RelionLibs)
am_tiltpair_plot_OBJECTS = src/apps/tiltpair_plot.$(OBJEXT)
tiltpair_plot_OBJECTS = $(am_tiltpair_plot_OBJECTS)
tiltpair_plot_DEPENDENCIES = $(RelionLibs)
SCRIPTS = $(dist_bin_SCRIPTS) $(dist_noinst_SCRIPTS)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(librelion_1.4_la_SOURCES) \
	$(autopick_SOURCES) $(autopick_mpi_SOURCES) $(display_SOURCES) \
	$(find_tiltpairs_SOURCES) $(image_handler_SOURCES) \
	$(maingui_SOURCES) $(manualpick_SOURCES) \
	$(mask_create_SOURCES) $(particle_polish_SOURCES) \
	$(particle_polish_mpi_SOURCES) \
	$(particle_segmentation_SOURCES) \
	$(particle_segmentation_mpi_SOURCES) $(particle_sort_SOURCES) \
	$(particle_sort_mpi_SOURCES) $(postprocess_SOURCES) \
	$(preprocess_SOURCES) $(preprocess_mpi_SOURCES) \
	$(project_SOURCES) $(reconstruct_SOURCES) $(refine_SOURCES) \
	$(refine_mpi_SOURCES) $(run_ctffind_SOURCES) \
	$(run_ctffind_mpi_SOURCES) $(stack_create_SOURCES) \
	$(star_compare_SOURCES) $(subtract_micrograph_SOURCES) \
	$(subtract_micrograph_mpi_SOURCES) $(tiltpair_plot_SOURCES)
DIST_SOURCES = $(am__librelion_1.4_la_SOURCES_DIST) \
	$(autopick_SOURCES) $(autopick_mpi_SOURCES) $(display_SOURCES) \
	$(find_tiltpairs_SOURCES) $(image_handler_SOURCES) \
	$(maingui_SOURCES) $(manualpick_SOURCES) \
	$(mask_create_SOURCES) $(particle_polish_SOURCES) \
	$(particle_polish_mpi_SOURCES) \
	$(particle_segmentation_SOURCES) \
	$(particle_segmentation_mpi_SOURCES) $(particle_sort_SOURCES) \
	$(particle_sort_mpi_SOURCES) $(postprocess_SOURCES) \
	$(preprocess_SOURCES) $(preprocess_mpi_SOURCES) \
	$(project_SOURCES) $(reconstruct_SOURCES) $(refine_SOURCES) \
	$(refine_mpi_SOURCES) $(run_ctffind_SOURCES) \
	$(run_ctffind_mpi_SOURCES) $(stack_create_SOURCES) \
	$(star_compare_SOURCES) $(subtract_micrograph_SOURCES) \
	$(subtract_micrograph_mpi_SOURCES) $(tiltpair_plot_SOURCES)
DATA = $(pkgconfig_DATA)
am__nobase_relion_include_HEADERS_DIST = relion.h src/args.h \
	src/assembly.h src/autopicker.h src/backprojector.h \
	src/complex.h src/ctf.h src/ctffind_runner.h src/displayer.h \
	src/error.h src/euler.h src/exp_model.h src/fftw.h \
	src/filename.h src/funcs.h src/gcc_version.h src/gui_entries.h \
	src/gui_jobwindow.h src/gui_mainwindow.h \
	src/healpix_sampling.h src/image.h src/macros.h src/mask.h \
	src/matrix1d.h src/matrix2d.h src/memory.h \
	src/metadata_container.h src/metadata_label.h \
	src/metadata_table.h src/ml_model.h src/ml_optimiser.h \
	src/multidim_array.h src/numerical_recipes.h src/parallel.h \
	src/particle_polisher.h src/particle_sorter.h \
	src/particle_segmenter.h src/subtractingmic.h \
	src/postprocessing.h src/preprocessing.h src/projector.h \
	src/rwIMAGIC.h src/rwMRC.h src/rwSPIDER.h src/strings.h \
	src/symmetries.h src/tabfuncs.h src/time.h \
	src/transformations.h src/Healpix_2.15a/arr.h \
	src/Healpix_2.15a/cxxutils.h src/Healpix_2.15a/datatypes.h \
	src/Healpix_2.15a/geom_utils.h src/Healpix_2.15a/lsconstants.h \
	src/Healpix_2.15a/message_error.h \
	src/Healpix_2.15a/openmp_support.h \
	src/Healpix_2.15a/pointing.h src/Healpix_2.15a/vec3.h \
	src/Healpix_2.15a/healpix_base.h src/mpi.h \
	src/autopicker_mpi.h src/ctffind_runner_mpi.h \
	src/particle_polisher_mpi.h src/particle_sorter_mpi.h \
	src/particle_segmenter_mpi.h src/subtractingmic_mpi.h \
	src/preprocessing_mpi.h src/ml_optimiser_mpi.h \
	src/manualpicker.h
HEADERS = $(nobase_relion_include_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/zhouqiang/softwares/relion-1.4-seg/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/zhouqiang/softwares/relion-1.4-seg/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/zhouqiang/softwares/relion-1.4-seg/missing --run autoconf
AUTOHEADER = ${SHELL} /home/zhouqiang/softwares/relion-1.4-seg/missing --run autoheader
AUTOMAKE = ${SHELL} /home/zhouqiang/softwares/relion-1.4-seg/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = -I/home/zhouqiang/softwares/relion-1.4-seg/include -I/home/zhouqiang/softwares/relion-1.4-seg/include -I/usr/include/freetype2 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT -fpic
CXX = mpic++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = -L/home/zhouqiang/softwares/relion-1.4-seg/lib -L/home/zhouqiang/softwares/relion-1.4-seg/lib -Wl,-rpath,/home/zhouqiang/softwares/relion-1.4-seg/lib -lfltk -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11
LIBOBJS = 
LIBS = -lfftw3_threads -lfftw3 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/zhouqiang/softwares/relion-1.4-seg/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
MPICXX = mpic++
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = relion
PACKAGE_BUGREPORT = scheres@mrc-lmb.cam.ac.uk
PACKAGE_NAME = relion
PACKAGE_STRING = relion 1.4
PACKAGE_TARNAME = relion
PACKAGE_VERSION = 1.4
PATH_SEPARATOR = :
RANLIB = ranlib
RELION_API_VERSION = 1.4
RELION_SO_VERSION = 1:4:0
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 1.4
abs_builddir = /home/zhouqiang/softwares/relion-1.4-seg
abs_srcdir = /home/zhouqiang/softwares/relion-1.4-seg
abs_top_builddir = /home/zhouqiang/softwares/relion-1.4-seg
abs_top_srcdir = /home/zhouqiang/softwares/relion-1.4-seg
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/zhouqiang/softwares/relion-1.4-seg/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /home/zhouqiang/softwares/relion-1.4-seg
program_transform_name = s,^,relion_,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}
dist_noinst_SCRIPTS = autogen.sh

# Install my_script in $(bindir) and distribute it.
dist_bin_SCRIPTS = \
scripts/star_datablock_ctfdat \
scripts/star_datablock_stack \
scripts/star_datablock_singlefiles \
scripts/star_loopheader \
scripts/star_plottable \
scripts/star_printtable \
scripts/qsub.csh


### Include tar.gz of FFTW and FLTK in distribution, as well as all source files for the GUI
EXTRA_DIST = INSTALL.sh \
external/fftw-3.2.2.tar.gz \
external/fltk-1.3.0.tar.gz 


###############################################################################
#
# Core library
#
###############################################################################
lib_LTLIBRARIES = librelion-1.4.la
librelion_1.4_la_SOURCES = src/args.cpp \
	src/assembly.cpp src/autopicker.cpp src/backprojector.cpp \
	src/complex.cpp src/ctf.cpp src/ctffind_runner.cpp \
	src/error.cpp src/euler.cpp src/exp_model.cpp src/fftw.cpp \
	src/filename.cpp src/funcs.cpp src/healpix_sampling.cpp \
	src/image.cpp src/mask.cpp src/matrix1d.cpp src/matrix2d.cpp \
	src/memory.cpp src/metadata_container.cpp \
	src/metadata_label.cpp src/metadata_table.cpp src/ml_model.cpp \
	src/ml_optimiser.cpp src/multidim_array.cpp \
	src/numerical_recipes.cpp src/parallel.cpp \
	src/particle_polisher.cpp src/particle_sorter.cpp \
	src/particle_segmenter.cpp src/subtractingmic.cpp \
	src/postprocessing.cpp src/preprocessing.cpp src/projector.cpp \
	src/strings.cpp src/symmetries.cpp src/tabfuncs.cpp \
	src/time.cpp src/transformations.cpp \
	src/Healpix_2.15a/cxxutils.cc \
	src/Healpix_2.15a/healpix_base.cc $(am__append_1) \
	$(am__append_3)
relion_includedir = $(includedir)/relion-$(RELION_API_VERSION)
nobase_relion_include_HEADERS = relion.h src/args.h src/assembly.h \
	src/autopicker.h src/backprojector.h src/complex.h src/ctf.h \
	src/ctffind_runner.h src/displayer.h src/error.h src/euler.h \
	src/exp_model.h src/fftw.h src/filename.h src/funcs.h \
	src/gcc_version.h src/gui_entries.h src/gui_jobwindow.h \
	src/gui_mainwindow.h src/healpix_sampling.h src/image.h \
	src/macros.h src/mask.h src/matrix1d.h src/matrix2d.h \
	src/memory.h src/metadata_container.h src/metadata_label.h \
	src/metadata_table.h src/ml_model.h src/ml_optimiser.h \
	src/multidim_array.h src/numerical_recipes.h src/parallel.h \
	src/particle_polisher.h src/particle_sorter.h \
	src/particle_segmenter.h src/subtractingmic.h \
	src/postprocessing.h src/preprocessing.h src/projector.h \
	src/rwIMAGIC.h src/rwMRC.h src/rwSPIDER.h src/strings.h \
	src/symmetries.h src/tabfuncs.h src/time.h \
	src/transformations.h src/Healpix_2.15a/arr.h \
	src/Healpix_2.15a/cxxutils.h src/Healpix_2.15a/datatypes.h \
	src/Healpix_2.15a/geom_utils.h src/Healpix_2.15a/lsconstants.h \
	src/Healpix_2.15a/message_error.h \
	src/Healpix_2.15a/openmp_support.h \
	src/Healpix_2.15a/pointing.h src/Healpix_2.15a/vec3.h \
	src/Healpix_2.15a/healpix_base.h $(am__append_2) \
	$(am__append_4)
librelion_1.4_la_LDFLAGS = -version-info $(RELION_SO_VERSION) $(FFT_LIBS)
relion_libincludedir = $(libdir)/relion-$(RELION_API_VERSION)/include
pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = relion-$(RELION_API_VERSION).pc
RelionLibs = librelion-$(RELION_API_VERSION).la 
refine_SOURCES = src/apps/refine.cpp
refine_LDADD = $(RelionLibs) 
refine_mpi_SOURCES = src/apps/refine_mpi.cpp
refine_mpi_LDADD = $(RelionLibs)
reconstruct_SOURCES = src/apps/reconstruct.cpp
reconstruct_LDADD = $(RelionLibs)
project_SOURCES = src/apps/project.cpp
project_LDADD = $(RelionLibs)
postprocess_SOURCES = src/apps/postprocess.cpp
postprocess_LDADD = $(RelionLibs)
preprocess_SOURCES = src/apps/preprocess.cpp
preprocess_LDADD = $(RelionLibs)
preprocess_mpi_SOURCES = src/apps/preprocess_mpi.cpp
preprocess_mpi_LDADD = $(RelionLibs)
autopick_SOURCES = src/apps/autopick.cpp
autopick_LDADD = $(RelionLibs)
autopick_mpi_SOURCES = src/apps/autopick_mpi.cpp
autopick_mpi_LDADD = $(RelionLibs)
manualpick_SOURCES = src/apps/manualpick.cpp
manualpick_LDADD = $(RelionLibs)
particle_polish_SOURCES = src/apps/particle_polish.cpp
particle_polish_LDADD = $(RelionLibs)
particle_polish_mpi_SOURCES = src/apps/particle_polish_mpi.cpp
particle_polish_mpi_LDADD = $(RelionLibs)
particle_sort_SOURCES = src/apps/particle_sort.cpp
particle_sort_LDADD = $(RelionLibs)
particle_sort_mpi_SOURCES = src/apps/particle_sort_mpi.cpp
particle_sort_mpi_LDADD = $(RelionLibs)
particle_segmentation_SOURCES = src/apps/particle_segmentation.cpp
particle_segmentation_LDADD = $(RelionLibs)
particle_segmentation_mpi_SOURCES = src/apps/particle_segmentation_mpi.cpp
particle_segmentation_mpi_LDADD = $(RelionLibs)
subtract_micrograph_SOURCES = src/apps/subtract_micrograph.cpp
subtract_micrograph_LDADD = $(RelionLibs)
subtract_micrograph_mpi_SOURCES = src/apps/subtract_micrograph_mpi.cpp
subtract_micrograph_mpi_LDADD = $(RelionLibs)
run_ctffind_SOURCES = src/apps/run_ctffind.cpp
run_ctffind_LDADD = $(RelionLibs)
run_ctffind_mpi_SOURCES = src/apps/run_ctffind_mpi.cpp
run_ctffind_mpi_LDADD = $(RelionLibs)
star_compare_SOURCES = src/apps/star_compare.cpp
star_compare_LDADD = $(RelionLibs)
display_SOURCES = src/apps/display.cpp
display_LDADD = $(RelionLibs)
maingui_SOURCES = src/apps/maingui.cpp
maingui_LDADD = $(RelionLibs)
mask_create_SOURCES = src/apps/mask_create.cpp
mask_create_LDADD = $(RelionLibs)
stack_create_SOURCES = src/apps/stack_create.cpp
stack_create_LDADD = $(RelionLibs)
image_handler_SOURCES = src/apps/image_handler.cpp
image_handler_LDADD = $(RelionLibs)
find_tiltpairs_SOURCES = src/apps/find_tiltpairs.cpp
find_tiltpairs_LDADD = $(RelionLibs)
tiltpair_plot_SOURCES = src/apps/tiltpair_plot.cpp
tiltpair_plot_LDADD = $(RelionLibs)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cc .cpp .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
relion-${RELION_API_VERSION}.pc: $(top_builddir)/config.status $(srcdir)/relion.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/args.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/assembly.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/autopicker.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/backprojector.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/complex.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ctf.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ctffind_runner.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/error.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/euler.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/exp_model.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/fftw.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/filename.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/funcs.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/healpix_sampling.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/image.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/mask.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/matrix1d.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/matrix2d.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/memory.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/metadata_container.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/metadata_label.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/metadata_table.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/ml_model.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ml_optimiser.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/multidim_array.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/numerical_recipes.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/parallel.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/particle_polisher.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/particle_sorter.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/particle_segmenter.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/subtractingmic.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/postprocessing.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/preprocessing.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/projector.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/strings.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/symmetries.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/tabfuncs.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/time.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/transformations.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/Healpix_2.15a/$(am__dirstamp):
	@$(MKDIR_P) src/Healpix_2.15a
	@: > src/Healpix_2.15a/$(am__dirstamp)
src/Healpix_2.15a/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/Healpix_2.15a/$(DEPDIR)
	@: > src/Healpix_2.15a/$(DEPDIR)/$(am__dirstamp)
src/Healpix_2.15a/cxxutils.lo: src/Healpix_2.15a/$(am__dirstamp) \
	src/Healpix_2.15a/$(DEPDIR)/$(am__dirstamp)
src/Healpix_2.15a/healpix_base.lo: src/Healpix_2.15a/$(am__dirstamp) \
	src/Healpix_2.15a/$(DEPDIR)/$(am__dirstamp)
src/mpi.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/autopicker_mpi.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/ctffind_runner_mpi.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/particle_polisher_mpi.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/particle_sorter_mpi.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/particle_segmenter_mpi.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/subtractingmic_mpi.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/preprocessing_mpi.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/ml_optimiser_mpi.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/displayer.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/gui_entries.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/gui_jobwindow.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/gui_mainwindow.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/manualpicker.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
librelion-1.4.la: $(librelion_1.4_la_OBJECTS) $(librelion_1.4_la_DEPENDENCIES) 
	$(librelion_1.4_la_LINK) -rpath $(libdir) $(librelion_1.4_la_OBJECTS) $(librelion_1.4_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
src/apps/$(am__dirstamp):
	@$(MKDIR_P) src/apps
	@: > src/apps/$(am__dirstamp)
src/apps/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/apps/$(DEPDIR)
	@: > src/apps/$(DEPDIR)/$(am__dirstamp)
src/apps/autopick.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
autopick$(EXEEXT): $(autopick_OBJECTS) $(autopick_DEPENDENCIES) 
	@rm -f autopick$(EXEEXT)
	$(CXXLINK) $(autopick_OBJECTS) $(autopick_LDADD) $(LIBS)
src/apps/autopick_mpi.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
autopick_mpi$(EXEEXT): $(autopick_mpi_OBJECTS) $(autopick_mpi_DEPENDENCIES) 
	@rm -f autopick_mpi$(EXEEXT)
	$(CXXLINK) $(autopick_mpi_OBJECTS) $(autopick_mpi_LDADD) $(LIBS)
src/apps/display.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
display$(EXEEXT): $(display_OBJECTS) $(display_DEPENDENCIES) 
	@rm -f display$(EXEEXT)
	$(CXXLINK) $(display_OBJECTS) $(display_LDADD) $(LIBS)
src/apps/find_tiltpairs.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
find_tiltpairs$(EXEEXT): $(find_tiltpairs_OBJECTS) $(find_tiltpairs_DEPENDENCIES) 
	@rm -f find_tiltpairs$(EXEEXT)
	$(CXXLINK) $(find_tiltpairs_OBJECTS) $(find_tiltpairs_LDADD) $(LIBS)
src/apps/image_handler.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
image_handler$(EXEEXT): $(image_handler_OBJECTS) $(image_handler_DEPENDENCIES) 
	@rm -f image_handler$(EXEEXT)
	$(CXXLINK) $(image_handler_OBJECTS) $(image_handler_LDADD) $(LIBS)
src/apps/maingui.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
maingui$(EXEEXT): $(maingui_OBJECTS) $(maingui_DEPENDENCIES) 
	@rm -f maingui$(EXEEXT)
	$(CXXLINK) $(maingui_OBJECTS) $(maingui_LDADD) $(LIBS)
src/apps/manualpick.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
manualpick$(EXEEXT): $(manualpick_OBJECTS) $(manualpick_DEPENDENCIES) 
	@rm -f manualpick$(EXEEXT)
	$(CXXLINK) $(manualpick_OBJECTS) $(manualpick_LDADD) $(LIBS)
src/apps/mask_create.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
mask_create$(EXEEXT): $(mask_create_OBJECTS) $(mask_create_DEPENDENCIES) 
	@rm -f mask_create$(EXEEXT)
	$(CXXLINK) $(mask_create_OBJECTS) $(mask_create_LDADD) $(LIBS)
src/apps/particle_polish.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
particle_polish$(EXEEXT): $(particle_polish_OBJECTS) $(particle_polish_DEPENDENCIES) 
	@rm -f particle_polish$(EXEEXT)
	$(CXXLINK) $(particle_polish_OBJECTS) $(particle_polish_LDADD) $(LIBS)
src/apps/particle_polish_mpi.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
particle_polish_mpi$(EXEEXT): $(particle_polish_mpi_OBJECTS) $(particle_polish_mpi_DEPENDENCIES) 
	@rm -f particle_polish_mpi$(EXEEXT)
	$(CXXLINK) $(particle_polish_mpi_OBJECTS) $(particle_polish_mpi_LDADD) $(LIBS)
src/apps/particle_segmentation.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
particle_segmentation$(EXEEXT): $(particle_segmentation_OBJECTS) $(particle_segmentation_DEPENDENCIES) 
	@rm -f particle_segmentation$(EXEEXT)
	$(CXXLINK) $(particle_segmentation_OBJECTS) $(particle_segmentation_LDADD) $(LIBS)
src/apps/particle_segmentation_mpi.$(OBJEXT):  \
	src/apps/$(am__dirstamp) src/apps/$(DEPDIR)/$(am__dirstamp)
particle_segmentation_mpi$(EXEEXT): $(particle_segmentation_mpi_OBJECTS) $(particle_segmentation_mpi_DEPENDENCIES) 
	@rm -f particle_segmentation_mpi$(EXEEXT)
	$(CXXLINK) $(particle_segmentation_mpi_OBJECTS) $(particle_segmentation_mpi_LDADD) $(LIBS)
src/apps/particle_sort.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
particle_sort$(EXEEXT): $(particle_sort_OBJECTS) $(particle_sort_DEPENDENCIES) 
	@rm -f particle_sort$(EXEEXT)
	$(CXXLINK) $(particle_sort_OBJECTS) $(particle_sort_LDADD) $(LIBS)
src/apps/particle_sort_mpi.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
particle_sort_mpi$(EXEEXT): $(particle_sort_mpi_OBJECTS) $(particle_sort_mpi_DEPENDENCIES) 
	@rm -f particle_sort_mpi$(EXEEXT)
	$(CXXLINK) $(particle_sort_mpi_OBJECTS) $(particle_sort_mpi_LDADD) $(LIBS)
src/apps/postprocess.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
postprocess$(EXEEXT): $(postprocess_OBJECTS) $(postprocess_DEPENDENCIES) 
	@rm -f postprocess$(EXEEXT)
	$(CXXLINK) $(postprocess_OBJECTS) $(postprocess_LDADD) $(LIBS)
src/apps/preprocess.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
preprocess$(EXEEXT): $(preprocess_OBJECTS) $(preprocess_DEPENDENCIES) 
	@rm -f preprocess$(EXEEXT)
	$(CXXLINK) $(preprocess_OBJECTS) $(preprocess_LDADD) $(LIBS)
src/apps/preprocess_mpi.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
preprocess_mpi$(EXEEXT): $(preprocess_mpi_OBJECTS) $(preprocess_mpi_DEPENDENCIES) 
	@rm -f preprocess_mpi$(EXEEXT)
	$(CXXLINK) $(preprocess_mpi_OBJECTS) $(preprocess_mpi_LDADD) $(LIBS)
src/apps/project.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
project$(EXEEXT): $(project_OBJECTS) $(project_DEPENDENCIES) 
	@rm -f project$(EXEEXT)
	$(CXXLINK) $(project_OBJECTS) $(project_LDADD) $(LIBS)
src/apps/reconstruct.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
reconstruct$(EXEEXT): $(reconstruct_OBJECTS) $(reconstruct_DEPENDENCIES) 
	@rm -f reconstruct$(EXEEXT)
	$(CXXLINK) $(reconstruct_OBJECTS) $(reconstruct_LDADD) $(LIBS)
src/apps/refine.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
refine$(EXEEXT): $(refine_OBJECTS) $(refine_DEPENDENCIES) 
	@rm -f refine$(EXEEXT)
	$(CXXLINK) $(refine_OBJECTS) $(refine_LDADD) $(LIBS)
src/apps/refine_mpi.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
refine_mpi$(EXEEXT): $(refine_mpi_OBJECTS) $(refine_mpi_DEPENDENCIES) 
	@rm -f refine_mpi$(EXEEXT)
	$(CXXLINK) $(refine_mpi_OBJECTS) $(refine_mpi_LDADD) $(LIBS)
src/apps/run_ctffind.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
run_ctffind$(EXEEXT): $(run_ctffind_OBJECTS) $(run_ctffind_DEPENDENCIES) 
	@rm -f run_ctffind$(EXEEXT)
	$(CXXLINK) $(run_ctffind_OBJECTS) $(run_ctffind_LDADD) $(LIBS)
src/apps/run_ctffind_mpi.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
run_ctffind_mpi$(EXEEXT): $(run_ctffind_mpi_OBJECTS) $(run_ctffind_mpi_DEPENDENCIES) 
	@rm -f run_ctffind_mpi$(EXEEXT)
	$(CXXLINK) $(run_ctffind_mpi_OBJECTS) $(run_ctffind_mpi_LDADD) $(LIBS)
src/apps/stack_create.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
stack_create$(EXEEXT): $(stack_create_OBJECTS) $(stack_create_DEPENDENCIES) 
	@rm -f stack_create$(EXEEXT)
	$(CXXLINK) $(stack_create_OBJECTS) $(stack_create_LDADD) $(LIBS)
src/apps/star_compare.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
star_compare$(EXEEXT): $(star_compare_OBJECTS) $(star_compare_DEPENDENCIES) 
	@rm -f star_compare$(EXEEXT)
	$(CXXLINK) $(star_compare_OBJECTS) $(star_compare_LDADD) $(LIBS)
src/apps/subtract_micrograph.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
subtract_micrograph$(EXEEXT): $(subtract_micrograph_OBJECTS) $(subtract_micrograph_DEPENDENCIES) 
	@rm -f subtract_micrograph$(EXEEXT)
	$(CXXLINK) $(subtract_micrograph_OBJECTS) $(subtract_micrograph_LDADD) $(LIBS)
src/apps/subtract_micrograph_mpi.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
subtract_micrograph_mpi$(EXEEXT): $(subtract_micrograph_mpi_OBJECTS) $(subtract_micrograph_mpi_DEPENDENCIES) 
	@rm -f subtract_micrograph_mpi$(EXEEXT)
	$(CXXLINK) $(subtract_micrograph_mpi_OBJECTS) $(subtract_micrograph_mpi_LDADD) $(LIBS)
src/apps/tiltpair_plot.$(OBJEXT): src/apps/$(am__dirstamp) \
	src/apps/$(DEPDIR)/$(am__dirstamp)
tiltpair_plot$(EXEEXT): $(tiltpair_plot_OBJECTS) $(tiltpair_plot_DEPENDENCIES) 
	@rm -f tiltpair_plot$(EXEEXT)
	$(CXXLINK) $(tiltpair_plot_OBJECTS) $(tiltpair_plot_LDADD) $(LIBS)
install-dist_binSCRIPTS: $(dist_bin_SCRIPTS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(dist_bin_SCRIPTS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-dist_binSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_bin_SCRIPTS)'; test -n "$(bindir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/Healpix_2.15a/cxxutils.$(OBJEXT)
	-rm -f src/Healpix_2.15a/cxxutils.lo
	-rm -f src/Healpix_2.15a/healpix_base.$(OBJEXT)
	-rm -f src/Healpix_2.15a/healpix_base.lo
	-rm -f src/apps/autopick.$(OBJEXT)
	-rm -f src/apps/autopick_mpi.$(OBJEXT)
	-rm -f src/apps/display.$(OBJEXT)
	-rm -f src/apps/find_tiltpairs.$(OBJEXT)
	-rm -f src/apps/image_handler.$(OBJEXT)
	-rm -f src/apps/maingui.$(OBJEXT)
	-rm -f src/apps/manualpick.$(OBJEXT)
	-rm -f src/apps/mask_create.$(OBJEXT)
	-rm -f src/apps/particle_polish.$(OBJEXT)
	-rm -f src/apps/particle_polish_mpi.$(OBJEXT)
	-rm -f src/apps/particle_segmentation.$(OBJEXT)
	-rm -f src/apps/particle_segmentation_mpi.$(OBJEXT)
	-rm -f src/apps/particle_sort.$(OBJEXT)
	-rm -f src/apps/particle_sort_mpi.$(OBJEXT)
	-rm -f src/apps/postprocess.$(OBJEXT)
	-rm -f src/apps/preprocess.$(OBJEXT)
	-rm -f src/apps/preprocess_mpi.$(OBJEXT)
	-rm -f src/apps/project.$(OBJEXT)
	-rm -f src/apps/reconstruct.$(OBJEXT)
	-rm -f src/apps/refine.$(OBJEXT)
	-rm -f src/apps/refine_mpi.$(OBJEXT)
	-rm -f src/apps/run_ctffind.$(OBJEXT)
	-rm -f src/apps/run_ctffind_mpi.$(OBJEXT)
	-rm -f src/apps/stack_create.$(OBJEXT)
	-rm -f src/apps/star_compare.$(OBJEXT)
	-rm -f src/apps/subtract_micrograph.$(OBJEXT)
	-rm -f src/apps/subtract_micrograph_mpi.$(OBJEXT)
	-rm -f src/apps/tiltpair_plot.$(OBJEXT)
	-rm -f src/args.$(OBJEXT)
	-rm -f src/args.lo
	-rm -f src/assembly.$(OBJEXT)
	-rm -f src/assembly.lo
	-rm -f src/autopicker.$(OBJEXT)
	-rm -f src/autopicker.lo
	-rm -f src/autopicker_mpi.$(OBJEXT)
	-rm -f src/autopicker_mpi.lo
	-rm -f src/backprojector.$(OBJEXT)
	-rm -f src/backprojector.lo
	-rm -f src/complex.$(OBJEXT)
	-rm -f src/complex.lo
	-rm -f src/ctf.$(OBJEXT)
	-rm -f src/ctf.lo
	-rm -f src/ctffind_runner.$(OBJEXT)
	-rm -f src/ctffind_runner.lo
	-rm -f src/ctffind_runner_mpi.$(OBJEXT)
	-rm -f src/ctffind_runner_mpi.lo
	-rm -f src/displayer.$(OBJEXT)
	-rm -f src/displayer.lo
	-rm -f src/error.$(OBJEXT)
	-rm -f src/error.lo
	-rm -f src/euler.$(OBJEXT)
	-rm -f src/euler.lo
	-rm -f src/exp_model.$(OBJEXT)
	-rm -f src/exp_model.lo
	-rm -f src/fftw.$(OBJEXT)
	-rm -f src/fftw.lo
	-rm -f src/filename.$(OBJEXT)
	-rm -f src/filename.lo
	-rm -f src/funcs.$(OBJEXT)
	-rm -f src/funcs.lo
	-rm -f src/gui_entries.$(OBJEXT)
	-rm -f src/gui_entries.lo
	-rm -f src/gui_jobwindow.$(OBJEXT)
	-rm -f src/gui_jobwindow.lo
	-rm -f src/gui_mainwindow.$(OBJEXT)
	-rm -f src/gui_mainwindow.lo
	-rm -f src/healpix_sampling.$(OBJEXT)
	-rm -f src/healpix_sampling.lo
	-rm -f src/image.$(OBJEXT)
	-rm -f src/image.lo
	-rm -f src/manualpicker.$(OBJEXT)
	-rm -f src/manualpicker.lo
	-rm -f src/mask.$(OBJEXT)
	-rm -f src/mask.lo
	-rm -f src/matrix1d.$(OBJEXT)
	-rm -f src/matrix1d.lo
	-rm -f src/matrix2d.$(OBJEXT)
	-rm -f src/matrix2d.lo
	-rm -f src/memory.$(OBJEXT)
	-rm -f src/memory.lo
	-rm -f src/metadata_container.$(OBJEXT)
	-rm -f src/metadata_container.lo
	-rm -f src/metadata_label.$(OBJEXT)
	-rm -f src/metadata_label.lo
	-rm -f src/metadata_table.$(OBJEXT)
	-rm -f src/metadata_table.lo
	-rm -f src/ml_model.$(OBJEXT)
	-rm -f src/ml_model.lo
	-rm -f src/ml_optimiser.$(OBJEXT)
	-rm -f src/ml_optimiser.lo
	-rm -f src/ml_optimiser_mpi.$(OBJEXT)
	-rm -f src/ml_optimiser_mpi.lo
	-rm -f src/mpi.$(OBJEXT)
	-rm -f src/mpi.lo
	-rm -f src/multidim_array.$(OBJEXT)
	-rm -f src/multidim_array.lo
	-rm -f src/numerical_recipes.$(OBJEXT)
	-rm -f src/numerical_recipes.lo
	-rm -f src/parallel.$(OBJEXT)
	-rm -f src/parallel.lo
	-rm -f src/particle_polisher.$(OBJEXT)
	-rm -f src/particle_polisher.lo
	-rm -f src/particle_polisher_mpi.$(OBJEXT)
	-rm -f src/particle_polisher_mpi.lo
	-rm -f src/particle_segmenter.$(OBJEXT)
	-rm -f src/particle_segmenter.lo
	-rm -f src/particle_segmenter_mpi.$(OBJEXT)
	-rm -f src/particle_segmenter_mpi.lo
	-rm -f src/particle_sorter.$(OBJEXT)
	-rm -f src/particle_sorter.lo
	-rm -f src/particle_sorter_mpi.$(OBJEXT)
	-rm -f src/particle_sorter_mpi.lo
	-rm -f src/postprocessing.$(OBJEXT)
	-rm -f src/postprocessing.lo
	-rm -f src/preprocessing.$(OBJEXT)
	-rm -f src/preprocessing.lo
	-rm -f src/preprocessing_mpi.$(OBJEXT)
	-rm -f src/preprocessing_mpi.lo
	-rm -f src/projector.$(OBJEXT)
	-rm -f src/projector.lo
	-rm -f src/strings.$(OBJEXT)
	-rm -f src/strings.lo
	-rm -f src/subtractingmic.$(OBJEXT)
	-rm -f src/subtractingmic.lo
	-rm -f src/subtractingmic_mpi.$(OBJEXT)
	-rm -f src/subtractingmic_mpi.lo
	-rm -f src/symmetries.$(OBJEXT)
	-rm -f src/symmetries.lo
	-rm -f src/tabfuncs.$(OBJEXT)
	-rm -f src/tabfuncs.lo
	-rm -f src/time.$(OBJEXT)
	-rm -f src/time.lo
	-rm -f src/transformations.$(OBJEXT)
	-rm -f src/transformations.lo

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/args.Plo
include src/$(DEPDIR)/assembly.Plo
include src/$(DEPDIR)/autopicker.Plo
include src/$(DEPDIR)/autopicker_mpi.Plo
include src/$(DEPDIR)/backprojector.Plo
include src/$(DEPDIR)/complex.Plo
include src/$(DEPDIR)/ctf.Plo
include src/$(DEPDIR)/ctffind_runner.Plo
include src/$(DEPDIR)/ctffind_runner_mpi.Plo
include src/$(DEPDIR)/displayer.Plo
include src/$(DEPDIR)/error.Plo
include src/$(DEPDIR)/euler.Plo
include src/$(DEPDIR)/exp_model.Plo
include src/$(DEPDIR)/fftw.Plo
include src/$(DEPDIR)/filename.Plo
include src/$(DEPDIR)/funcs.Plo
include src/$(DEPDIR)/gui_entries.Plo
include src/$(DEPDIR)/gui_jobwindow.Plo
include src/$(DEPDIR)/gui_mainwindow.Plo
include src/$(DEPDIR)/healpix_sampling.Plo
include src/$(DEPDIR)/image.Plo
include src/$(DEPDIR)/manualpicker.Plo
include src/$(DEPDIR)/mask.Plo
include src/$(DEPDIR)/matrix1d.Plo
include src/$(DEPDIR)/matrix2d.Plo
include src/$(DEPDIR)/memory.Plo
include src/$(DEPDIR)/metadata_container.Plo
include src/$(DEPDIR)/metadata_label.Plo
include src/$(DEPDIR)/metadata_table.Plo
include src/$(DEPDIR)/ml_model.Plo
include src/$(DEPDIR)/ml_optimiser.Plo
include src/$(DEPDIR)/ml_optimiser_mpi.Plo
include src/$(DEPDIR)/mpi.Plo
include src/$(DEPDIR)/multidim_array.Plo
include src/$(DEPDIR)/numerical_recipes.Plo
include src/$(DEPDIR)/parallel.Plo
include src/$(DEPDIR)/particle_polisher.Plo
include src/$(DEPDIR)/particle_polisher_mpi.Plo
include src/$(DEPDIR)/particle_segmenter.Plo
include src/$(DEPDIR)/particle_segmenter_mpi.Plo
include src/$(DEPDIR)/particle_sorter.Plo
include src/$(DEPDIR)/particle_sorter_mpi.Plo
include src/$(DEPDIR)/postprocessing.Plo
include src/$(DEPDIR)/preprocessing.Plo
include src/$(DEPDIR)/preprocessing_mpi.Plo
include src/$(DEPDIR)/projector.Plo
include src/$(DEPDIR)/strings.Plo
include src/$(DEPDIR)/subtractingmic.Plo
include src/$(DEPDIR)/subtractingmic_mpi.Plo
include src/$(DEPDIR)/symmetries.Plo
include src/$(DEPDIR)/tabfuncs.Plo
include src/$(DEPDIR)/time.Plo
include src/$(DEPDIR)/transformations.Plo
include src/Healpix_2.15a/$(DEPDIR)/cxxutils.Plo
include src/Healpix_2.15a/$(DEPDIR)/healpix_base.Plo
include src/apps/$(DEPDIR)/autopick.Po
include src/apps/$(DEPDIR)/autopick_mpi.Po
include src/apps/$(DEPDIR)/display.Po
include src/apps/$(DEPDIR)/find_tiltpairs.Po
include src/apps/$(DEPDIR)/image_handler.Po
include src/apps/$(DEPDIR)/maingui.Po
include src/apps/$(DEPDIR)/manualpick.Po
include src/apps/$(DEPDIR)/mask_create.Po
include src/apps/$(DEPDIR)/particle_polish.Po
include src/apps/$(DEPDIR)/particle_polish_mpi.Po
include src/apps/$(DEPDIR)/particle_segmentation.Po
include src/apps/$(DEPDIR)/particle_segmentation_mpi.Po
include src/apps/$(DEPDIR)/particle_sort.Po
include src/apps/$(DEPDIR)/particle_sort_mpi.Po
include src/apps/$(DEPDIR)/postprocess.Po
include src/apps/$(DEPDIR)/preprocess.Po
include src/apps/$(DEPDIR)/preprocess_mpi.Po
include src/apps/$(DEPDIR)/project.Po
include src/apps/$(DEPDIR)/reconstruct.Po
include src/apps/$(DEPDIR)/refine.Po
include src/apps/$(DEPDIR)/refine_mpi.Po
include src/apps/$(DEPDIR)/run_ctffind.Po
include src/apps/$(DEPDIR)/run_ctffind_mpi.Po
include src/apps/$(DEPDIR)/stack_create.Po
include src/apps/$(DEPDIR)/star_compare.Po
include src/apps/$(DEPDIR)/subtract_micrograph.Po
include src/apps/$(DEPDIR)/subtract_micrograph_mpi.Po
include src/apps/$(DEPDIR)/tiltpair_plot.Po

.cc.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

.cpp.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf src/.libs src/_libs
	-rm -rf src/Healpix_2.15a/.libs src/Healpix_2.15a/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pkgconfigdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)"
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(pkgconfigdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(pkgconfigdir)" && rm -f $$files
install-nobase_relion_includeHEADERS: $(nobase_relion_include_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(relion_includedir)" || $(MKDIR_P) "$(DESTDIR)$(relion_includedir)"
	@list='$(nobase_relion_include_HEADERS)'; test -n "$(relion_includedir)" || list=; \
	$(am__nobase_list) | while read dir files; do \
	  xfiles=; for file in $$files; do \
	    if test -f "$$file"; then xfiles="$$xfiles $$file"; \
	    else xfiles="$$xfiles $(srcdir)/$$file"; fi; done; \
	  test -z "$$xfiles" || { \
	    test "x$$dir" = x. || { \
	      echo "$(MKDIR_P) '$(DESTDIR)$(relion_includedir)/$$dir'"; \
	      $(MKDIR_P) "$(DESTDIR)$(relion_includedir)/$$dir"; }; \
	    echo " $(INSTALL_HEADER) $$xfiles '$(DESTDIR)$(relion_includedir)/$$dir'"; \
	    $(INSTALL_HEADER) $$xfiles "$(DESTDIR)$(relion_includedir)/$$dir" || exit $$?; }; \
	done

uninstall-nobase_relion_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nobase_relion_include_HEADERS)'; test -n "$(relion_includedir)" || list=; \
	$(am__nobase_strip_setup); files=`$(am__nobase_strip)`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(relion_includedir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(relion_includedir)" && rm -f $$files

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(SCRIPTS) $(DATA) \
		$(HEADERS) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(relion_includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/Healpix_2.15a/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/Healpix_2.15a/$(am__dirstamp)
	-rm -f src/apps/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/apps/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR) src/Healpix_2.15a/$(DEPDIR) src/apps/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-nobase_relion_includeHEADERS \
	install-pkgconfigDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-dist_binSCRIPTS \
	install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR) src/Healpix_2.15a/$(DEPDIR) src/apps/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dist_binSCRIPTS \
	uninstall-libLTLIBRARIES \
	uninstall-nobase_relion_includeHEADERS uninstall-pkgconfigDATA

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool ctags dist dist-all dist-bzip2 dist-gzip \
	dist-lzma dist-shar dist-tarZ dist-xz dist-zip distcheck \
	distclean distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dist_binSCRIPTS install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man \
	install-nobase_relion_includeHEADERS install-pdf \
	install-pdf-am install-pkgconfigDATA install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-dist_binSCRIPTS \
	uninstall-libLTLIBRARIES \
	uninstall-nobase_relion_includeHEADERS uninstall-pkgconfigDATA


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
